profil:
  class: sfPropelORMRouteCollection
  options:
    model:                Profil
    module:               profil
    prefix_path:          /profil
    column:               id
    with_wildcard_routes: true

page:
  class: sfPropelORMRouteCollection
  options:
    model:                Page
    module:               page
    prefix_path:          /page
    column:               id
    with_wildcard_routes: true

homepage:
  url:   /
  param: { module: profil, action: viewProfil }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

default:
  url:		/:module/:action/*
