# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: page, action: index }

contact:
  url:	/contact
  param:	{ module: page, action: contact }

sent:
  url:	/sent
  param:	{ module: page, action: sent }

view_language:
  url:	/change/:language
  param:	{ module: page, action: changeLanguage }

page_slug:
  url:   /:slug
  param: { module: page, action: show }

