propel:
  page:
    id:						~
    name:					{ type: varchar, size: 255, required: true }
    slug:					{ type: varchar, size: 255, required: true }
    menu_index:		{ type: integer }
    content:			{ type: longvarchar }
    language:			{ type: varchar, size: 2, requried: true }
    published:		{ type: boolean }
    homepage:			{ type: boolean }

  profil:
    id:						~
    user_id:			{ type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onDelete: cascade }
    firstname:		{ type: varchar, size: 255 }
    lastname:			{ type: varchar, size: 255 }
    email:				{ type: varchar, size: 255 }
    birthdate:		{ type: date }
    phone:				{ type: varchar, size: 50 }